---
title: "A Practical Guide to Quantitative Finance Interviews (Zhou, X.)"
subtitle: "Summary of Selected Chapters"

author:
  name: "Yvan Richard"
  email: "yvan.richard2004@gmail.com"

date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true
    code-copy: true
    code-overflow: wrap
    html-math-method: katex

jupyter: python3
---

# Foreword

[to be completed]

# Brain Teasers

## Problem Simplification

The schema trained here is simple: whenever a problem appears to dauting to solve it as is, try to solve one of its reduced form.
Once you solved the first few steps, gradually increase the complexity to uncover the *general* solution.

### Screwy Pirates

**Problem**  

Five pirates $\{1, \cdots, 5\}$ looted a chest full of 100 gold coins. They agree on the following method to split the loot:
 
The most senior pirate, $5$, will propose a distribution of the coins: $(x_1, x_2, x_3, x_4, x_5)$ where $\sum_{k=1}^{5} x_k = 100$.
If **at least** $50\%$ of the pirates accept the split, the loot is divided as proposed. Otherwise, the pirate $5$ is killed and the procedure
repeats with pirate $4$. Given that each pirate is rational, wants to stay alive first and get as much gold as possible second, what will be the final split?

**Solution**

[to be completed]

### Tiger and sheep

**Problem**   

One hundred tigers and one sheep are put on an island where we only have grass. Both sheep and tigers can eat grass to survive.
Tigers prefer to eat sheep rather than grass, but want to survive first. Whenever a tiger eats a sheep, that tiger becomes a sheep. So if we start in the
initial situation and one tiger eats a sheep, we have $(1, 100) \to (1, 99)$. Given that all tigers are rational, will the sheep be eaten?

**Solution**

[to be completed]

## Logic Reasoning

### Birthday problem

**Problem**   

You and your colleagues know the following information (public knowledge).
Your boss $A$'s birthday is one of the following 10 dates:

```{txt}
March: 4, 5, 8
June: 4, 7
September: 1, 5
December: 1, 2, 8
```

$A$ told you **only** the month of his birthday, and told you colleague $C$ **only** the day.
After that you said:

"I don't know $A$'s birthday; C doesn't know either."

After hearing this, $C$ said:

"I did not know the date, but now I know it."

You smiled and said:

"Now, I know it too!".

What is the date of $A$'s birthday?

**Solution**

1. We don't know the date and knows that $C$ does not either. How is it possible for us to know this? Because we know that the date's day is **necessarily repeated**. Hence, the possible candidates month becomes: `March` and `September`. Once we communicate this, $C$ can also *infer* this.
2. $C$ was directly able to identify $A$'s birthday date. How? We need to remove all the dates with day `5`. Then, $C$ has enough information to find among: `Sep. 1`, `Mar. 4`, or `Mar. 8`. $C$ communicates.
3. Now, $A$ is able to find it, meaning that it must be `Sep. 1`.

### Card Game

**Problem**

A casino offers a card game using a normal deck of 52 cards.
The rule is that you turn over two cards each time. For each pair,
if both are black, they go to the dealer's pile, if both are red, to yours.
Otherwise, they are discarded. The process is repeated until we go through the 52 cards.
If you have **strictly** more cards in your pile, you win $\$$ 100; otherwise, nothing.
Being rational, how much are you willing to pay to play the game?

**Solution**

*Assumption 1: the cards are not drawn from the "dealer's pile"*.

This game is purely deterministic. Indeed, whenever we draw two red cards, we automatically loose one
opportunity to counter the black cards in the future (i.e. at least one pair of two black cards will
necessarily be drawn from the pile). Therefore, in the end, the two players end up with exactly the same
number of cards in their pile. However, since the house wins in the event of a draw, we will **always** loose.
As such, we should **not** invest any money in this game.


### Burning ropes

**Problem**

You have two different ropes $r1$ and $r2$. Each rope will take exactly one hour to burn. However,
both ropes have different densities at different points, so there is no guarantee that they will burn regularly.
Given that the density patterns are not necessarily the same for each rope, how do you use the two ropes to measure 45 minutes?

**Solution**

- For rope $r1$, we can light both ends of the rope so that it burns twice as fast: 30 minutes.
- Simultaneously, when we light both ends of $r1$, we light only one end of rope $r2$.
- Exactly when rope $r1$ has finished burning, we know that 30 minutes have passed. At this point, rope $r2$ would still take another 30 minutes to burn completely. However, if we light the other end of $r2$ now, it will take only half that time, so 15 minutes.
- Once $r2$ has finished burning, exactly 45 minutes will have passed.

### Defective Balls

**Problem**

You have 12 identical balls. One of the balls is heavier OR lighter than the rest (you
don't know which). Using just a balance that can only show you which side of the tray is
heavier, how can you determine which ball is the defective one with 3 measurements?

**Solution**

We put 6 balls on each side of the scale. We spot the heaviest group (the heavy ball is indicate by a $1$):

```{txt}
              \oooooo/
         /-x-/ 
\ooo1oo/   |
```

Now we only have 6 balls. We take 4 of these and put two on each side of the scale. We have three groups: $a$, $b$, and $c$.

```{txt}
               (b)                                    (a)        (b)
              \oo/                                   (oo)---x---(oo)
    (a)  /-x-/                                              |
    \1o/   |         (oo)   (c)                OR           |          (o1) (c)
```

The heaviest ball will be in one of the three groups and the operation allows to determine which one (as illustrated by the schema). Finally, we will only have two balls to measure.

### Trailing zeros

**Problem**

How many trailing zeros are there in $100!$?

**Solution**

A trailing 0 will appear once we multiply by 2 and 5. For instance:

$$
0! = 1, 1! = 1, 2! = 2, 3! = 6, 4! = 24, 5! = 120.
$$

Therefore, we need to count the number of paired $(2, 5)$ until reaching $100$. Evidently,
the number $2$ will appear far more often than the number $5$; thus, $5$ is an upper bound.
We now need to determine how many times the number $5$ appears.

First of all, we have 20 multiples of 5 until 100. However, when we multiply by 25, we have two
occurences of 5. This increases the count to 21. We also have $50 = 5 \times 5 \times 2$, so our count reaches 22.
We do not forget $75 = 5 \times 5 \times 3$. Then, $100 = 2 \times 5 \times 2 \times 5$. So our final count reaches 24.

We will have 24 trailing 0s in $100!$.

### Horse Race

**Problem**

There are 25 horses, each of which runs at a constant speed that is different from the
other horses. Since the track only has 5 lanes, each race can have at most 5 horses. If
you need to find the 3 fastest horses, what is the minimum number of races needed to
identify them?

**Solution**

`not completed`.


### Infinite Sequence

**Problem**

If `x^x^x^x^x^x^(...) = 2`, where `x^x` = $x^x$, what is $x$?

**Solution**

Let

$$
y = x^{x^{x^{x^{\cdot^{\cdot^\cdot}}}}}.
$$

We are given that $y=2$. Because removing the bottom $x$ from an infinite power sequence leaves the same sequence,

$$
y=x^y.
$$

Substituting $y=2$,

$$
2=x^2 \implies x = \sqrt{2}
$$


## Thinking Out of the Box

### Door to offer

**Problem**

We face two doors. Behind one door is our dream quant job offer, behind the other, an email starting with "Thank you for taking the time to consider opportunities at ...".
The doors are guarded by two interns, $A$ and $B$. One intern always tells the truth, one always lies but we don't know who does what. Given that you can only ask one closed question (yes/no) and you want to obtain the job, what question will you ask?

```{text}
                                  
          _A_           _B_        
         |  .|         |  .|        
_________|   |_________|   |________
```


**Solution**

"If I asked you whether this door leads to the offer, would you say yes?"

### Message delivery

**Problem**

You need  to communicate with your colleague in Greenwich via a messenger service.
Your documents are sent in a padlock box. Unfortunately the messenger service is not secure,
so anything inside an unlocked box will be lost (including any locks you place inside the box) during
the delivery. The high-security padlocks you and your colleague each use have only one key which the person placing
the lock owns. How can you securely send a document to your colleague?

**Solution**

Let us suppose that $A$ communicates with $B$ and $A$ is sending a document.

1. $A$ puts the document in the box and locks it with his padlock before sending it to $B$.
2. $B$ receives the box and also puts a padlock on before sending it back to $A$.
3. $A$ receives the box, removes his lock, and send it again to $B$.
4. $B$ unlocks his own lock and reads the document.


### Last ball

**Problem**

A bag has 20 blue balls and 14 red balls. Each time you randomly take two balls out. (Assume each ball in the bag has equal probability of being taken.) You do not put these two balls back. Instead, if both balls have the same color, you add a blue ball to the bag; if they have different colors, you add a red ball to the bag. Assume that you have an unlimited supply of blue and red balls. If you keep on repeating this process, what will be the color of the last ball left in the bag? What if the bag has 20 blue balls and 13 red balls instead?


**Solution**

This is also a purely deterministic game. Let us suppose that $(b, r)$ denotes the number of blue $b$, and red $r$ balls in the bag.
Let us suppose that at every round, we draw one red ball and one blue ball, we will go from $(20, 14)$ to $(0, 14)$. At this stage, we will
necessarily picking only same colored balls, so adding blue balls. Once we have only blue balls, we will progressively eliminate them until we have $0$.
The color of the last ball will be blue.

On the other hand, let us suppose that we have 13 red balls, i.e. an odd number of red balls. Let us suppose again the following move $(20, 13) \to (0, 13)$. In this case, there is no scenario in which
the red balls "cancel" each other out, we could arrive at $(6, 1)$ and then $(1, 1)$. That's the only scenario possible for ending the bag, so the last one will be red.


## Series Summation

### Clock pieces

**Problem**

A clock (numbered 1–12 clockwise) fell off the wall and broke into three pieces. You find that the sums of the numbers on each piece are equal. What are the numbers on each piece? (No strange-shaped piece is allowed.)

**Solution**

First, we can compute $sum_{i = 1}{12} = \frac{(12 + 1)(12)}{2} = \frac{156}{2} = 78$. This means that each piece will have its digits summing to $78/3 = 26$.
No we need to find the pieces, for instance: $11 + 12 + 1 + 2 = 26$. Then, we $5 + 6 + 7 + 8 = 26$, and with all the other pieces, we can still form one fragement equals to 26.

### Missing Integers

**Problem**

Let us suppose that we have 98 distinct integers $i \in [1, 100]$. How can we find the two missing ones?

**Solution**

We know that the complete sum is $101 \cdot 100 \cdot \frac{1}{2} = 5{,}050$. Let us suppose that $x$ is the sum of all the digits we have. Then,
we search for a pair $(d_1, d_2)$ where:

$$
d_1 + d_2 = 5{,}050 - x
$$

We also know that $d_1, d_2 < (d_1 + d_2)$ so this restrains the search space.











